### PR TITLE
Fixed: Re-clicking on Upload file button & cancelling it gives error (#85zrhfp4c) 

### LINKED ISSUE #121: Re-clicking on "Upload" file button & cancelling it gives error.
## Current behavior

When we upload a file for the second time & click on upload button to upload a new file, instead of uploading a file if we click on cancel button, it gives errors.
Screenshot 2022-12-28 at 12 38 27 PM

## Expected behavior

On clicking "Cancel" button second time, it should give any error

## Steps to reproduce the issue

1. Click on **Upload** button on "Purchase Order" page.
2. Upload a file.
3. Click on **Upload** button again & this time instead of uploading a file. Click on "**Cancel**" button.
4. Check console for errors.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

### PR DESCRIPTION
**Pull request by k2maan**
### Related Issues

Closes #121 

### Short Description and Why It's Useful

Unwanted error is removed, also if we decide not to upload a file, current file says selected.

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/import#contribution-guideline)

### CODE REVIEW

File: src/views/PurchaseOrder.vue [hunk 1]
```diff
@@ -151,14 +151,15 @@ export default defineComponent({
...
-        if(this.file){
-          showToast(translate("File uploaded successfully"));
+        const file = event.target.files[0];
+        if(file){
+          this.file = file;
           this.parseFile();
           this.store.dispatch('order/updateFileName', this.file.name);
+          showToast(translate("File uploaded successfully"));
         }
         else {
```
Comment (ymaheshwari1) [inline src/views/PurchaseOrder.vue:161]: Improve code formatting

File: src/views/PurchaseOrder.vue [hunk 2]
```diff
@@ -151,14 +151,15 @@ export default defineComponent({
...
-          showToast(translate("Something went wrong. Please try again"));
+          showToast(translate("No new file upload. Please try again"));
```
Comment (ymaheshwari1) [inline src/views/PurchaseOrder.vue:162]: Ir works when trying to change the file first time, but if we repeat changing the file more than once, then it does not work.

**Review by ymaheshwari1 — CHANGES_REQUESTED** [review]

**Comment by k2maan** [comment]
After discussion, it is concluded that we'll not implement the functionality to show the toast even after not selecting the file for the first time. The toast will appear only for the first time.

**Review by adityasharma7 — APPROVED** [review]
