### PR TITLE
fix: search not working on PO review page(#85zrmf7ed)

### LINKED ISSUE #180: Search for Shopify ID on PO review page not working
## Current behavior
 When HC product identifier is Shopify ID and the PO is uploaded with that ID, search with the Shopify ID is not supported.

## Expected behavior
 Product should be searched by Shopify ID. 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

### PR DESCRIPTION
**Pull request by disha1202**
### Related Issues

Closes #180 

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/import#contribution-guideline)

### CODE REVIEW

File: src/views/PurchaseOrderReview.vue [hunk 1]
```diff
@@ -18,7 +18,7 @@
     <ion-content :fullscreen="true">
       <div class="header">
         <div class="search">
-          <ion-searchbar :placeholder="$t('Search products')" v-model="queryString" v-on:keyup.enter="queryString = $event.target.value; searchProduct(queryString)" />
+          <ion-searchbar :placeholder="$t('Search products')" v-on:keyup.enter="queryString = $event.target.value; searchProduct(queryString)" />
```
Comment (k2maan) [inline src/views/PurchaseOrderReview.vue:21]: We can use shorthand for v-on.

File: src/views/PurchaseOrderReview.vue [hunk 2]
```diff
@@ -189,19 +197,35 @@ export default defineComponent({
         component: MissingSkuModal,
         componentProps: { 'unidentifiedItems': this.purchaseOrders.unidentifiedItems }
       });
+      missingSkuModal.onDidDismiss().then(() => {
```
Comment (k2maan) [inline src/views/PurchaseOrderReview.vue:200]: We can use async-await syntax here

File: src/views/PurchaseOrderReview.vue [hunk 3]
```diff
@@ -189,19 +197,35 @@ export default defineComponent({
...
+          return item.pseudoId === product.pseudoId;
+        })
+      }
     },
     async openDateTimeParseErrorModal() {
       const dateTimeParseErrorModal = await modalController.create({
         component: DateTimeParseErrorModal,
         componentProps: { numberOfItems: Object.values(this.purchaseOrders.parsed).flat().length, numberOfPos: Object.keys(this.purchaseOrders.parsed).length }
       });
+      dateTimeParseErrorModal.onDidDismiss().then(() => {
```
Comment (k2maan) [inline src/views/PurchaseOrderReview.vue:226]: We can use async-await syntax here

File: src/views/PurchaseOrderReview.vue [hunk 4]
```diff
@@ -51,13 +51,21 @@
...
       </div>
-      <div v-for="(po, poId) in purchaseOrders.parsed" :key="poId" >
-        <PurchaseOrderDetail v-if="segmentSelected === poId" :itemsByPoId="{[poId]: po}" :purchaseOrders="purchaseOrders" />
+
+      <div v-else>
+        <div v-if="segmentSelected === 'all'">
+          <PurchaseOrderDetail :purchaseOrders="purchaseOrders" :itemsByPoId ="purchaseOrders.parsed"  />
+        </div>
+        <div v-for="(po, poId) in purchaseOrders.parsed" :key="poId" >
+          <PurchaseOrderDetail v-if="segmentSelected === poId" :itemsByPoId="{[poId]: po}" :purchaseOrders="purchaseOrders" />
```
Comment (k2maan) [inline src/views/PurchaseOrderReview.vue:63]: Searching pseudoId and changing segments is not honouring the PO segment to search and is searching on all POs. For instance, if I have 2 POs and I search for something from PO1 in all segments and change the segment to PO2, the searched product will appear there from PO1.

File: src/views/PurchaseOrderReview.vue (hunk 1 above)
Comment (disha1202) [reply src/views/PurchaseOrderReview.vue]: Updated

File: src/views/PurchaseOrderReview.vue (hunk 2 above)
Comment (disha1202) [reply src/views/PurchaseOrderReview.vue]: Updated

File: src/views/PurchaseOrderReview.vue (hunk 4 above)
Comment (disha1202) [reply src/views/PurchaseOrderReview.vue:67]: Fixed.

Comment (disha1202) [reply src/views/PurchaseOrderReview.vue:67]: Fixed.

File: src/views/PurchaseOrderReview.vue [hunk 5]
```diff
@@ -51,13 +51,25 @@
...
       </div>
-      <div v-if="segmentSelected === 'all'">
-        <PurchaseOrderDetail :purchaseOrders="purchaseOrders" :itemsByPoId ="purchaseOrders.parsed"  />
+      <div v-if="searchedProduct?.pseudoId">
+        <PurchaseOrderDetail :purchaseOrders="purchaseOrders" :itemsByPoId ="{[searchedProduct?.orderId]: [searchedProduct]}"  />
       </div>
-      <div v-for="(po, poId) in purchaseOrders.parsed" :key="poId" >
-        <PurchaseOrderDetail v-if="segmentSelected === poId" :itemsByPoId="{[poId]: po}" :purchaseOrders="purchaseOrders" />
+
+      <div class="empty-state" v-else-if="queryString">
```
Comment (k2maan) [inline src/views/PurchaseOrderReview.vue:58]: Are there any specific reasons for using the 'empty-state' class instead of Ionic's CSS utility class for center alignment?

**Review by adityasharma7 — APPROVED** [review]
