### PR TITLE
Fixed: Cursor should change to pointer for drop down action menu for records(#85zrgxywt)

### LINKED ISSUE #64: Cursor should change to pointer for drop down action menu for records
Steps to navigate to Purchase Order Details page

1. Login into application
OMS: dev-apps
Username: aaron.wagner
password: Aaron@123

2. Upload the below CSV:
[DM12234_SUMPO111111.csv](https://github.com/hotwax/import/files/9725012/DM12234_SUMPO111111.csv)

3. Select appropriate fields and click on Review
image

4. Open action menu for individual records, actions should cursor as pointer
image

### PR DESCRIPTION
**Pull request by disha1202**
### Related Issues

Closes #64 

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/import#contribution-guideline)

### CODE REVIEW

File: src/components/ProductPopover.vue [hunk 1]
```diff
@@ -5,11 +5,11 @@
     </ion-item>
     <ion-item lines="none" @click="revert">
       <ion-icon slot="start" :icon="arrowUndoOutline" />
-      <ion-label>{{ $t('Reset') }}</ion-label>
+      <ion-label class="pointer">{{ $t('Reset') }}</ion-label>
```
Comment (ymaheshwari1) [inline src/components/ProductPopover.vue:8]: We can add button to `ion-item` and then we don't need to use class.

**Review by ymaheshwari1 — CHANGES_REQUESTED** [review]

File: src/components/ProductPopover.vue (hunk 1 above)
Comment (adityasharma7) [reply src/components/ProductPopover.vue:8]: https://ionicframework.com/docs/api/item#clickable-items

**Review by adityasharma7 — APPROVED** [review]
