### PR TITLE
fix: Deselecting a single product from a group, deselects all variants(#2kbkwnr)

### LINKED ISSUE #82: Deselecting a single product from a group, deselects all variants
## Current behavior

When deselecting a single product from a group of products, all the products in that group gets deselected

## Expected behavior

Deselecting a single product from the parents group should only deselect that product and virtual product.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

### PR DESCRIPTION
**Pull request by disha1202**
Closes #82

### CODE REVIEW

File: src/views/OrderDetail.vue [hunk 1]
```diff
@@ -97,7 +97,7 @@
 
           <div />
           
-          <ion-checkbox :checked="isParentProductChecked(id)" @ionChange="selectParentProduct(id, $event)" />
+          <ion-checkbox :checked="isParentProductChecked(id)" @click="handleChange(true)" @ionChange="selectParentProduct(id, $event)" />
```
Comment (adityasharma7) [inline src/views/OrderDetail.vue:100]: Instead of having separate method, I think we could call `selectParentProduct(id, $event)` on click

**Review by adityasharma7 — CHANGES_REQUESTED** [review]

File: src/views/OrderDetail.vue (hunk 1 above)
Comment (disha1202) [reply src/views/OrderDetail.vue:100]: If we call selectParentProduct on click it will not select/deselect all the variants as we won't be able to access the current value of checkbox

**Review by adityasharma7 — APPROVED** [review]
