### PR TITLE
Fixed: The save mapping input value should be empty after save action(#85zrh7473)

### LINKED ISSUE #123: The save mapping input value should be empty after save action
## Current behavior

There is no way to verify whether the mapping has been saved or not. When the user clicks on the save button multiple times multiple mapppings with same name are created and stored.

## Expected behavior

When the user clicks on save button, after the save action mapping name input should be set empty as this will disable the save mapping button, it will restrict the user from saving the same mapping multiple time.

## Steps to reproduce the issue

1. Log into the application.
2. Upload CSV
3. Map fields
4. Enter mapping name
5. Click on save mapping multiple time
6. Click on field mapping drop down 

It will display multiple mappings with the same name.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

### PR DESCRIPTION
**Pull request by shashwatbangar**
### Related Issues

Closes #123 

### Screenshots of Visual Changes before/after (If There Are Any)

https://user-images.githubusercontent.com/62360781/210237518-e6c26869-6e4d-4df1-ba7f-eba161d73e6a.mov

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/import#contribution-guideline)

### CODE REVIEW

File: src/views/PurchaseOrder.vue [hunk 1]
```diff
@@ -145,6 +145,7 @@ export default defineComponent({
           showToast(translate("Map all fields"));
           return
         }
+        this.mappingName = "";
```
Comment (ymaheshwari1) [inline src/views/PurchaseOrder.vue:148]: When assigning empty value to the mappingName here, it will save the mapping with an empty name in localStorage.

**Review by ymaheshwari1 — CHANGES_REQUESTED** [review]

File: src/views/PurchaseOrder.vue (hunk 1 above)
Comment (shashwatbangar) [reply src/views/PurchaseOrder.vue]: Yes sir. Fixed it.

**Review by k2maan — APPROVED** [review]
