### PR TITLE
Fixed: Mapping not saved in case there are no previous mappings (#85zrv32ug)

### LINKED ISSUE #193: Mapping saved the first time after login fails
## Current behavior
When a user logs in for the first time and creates a mapping, it does not save. However, when we logout and login again, the earlier saved mapping is visible.
It is only the first time user logs in that the mapping cannot be saved, the second time we are able to create mappings and save them successfully.
We have tested this on demo-oms and dev-hc instances.

## Expected behavior
The user should be able to log in and save the mapping without any fail message.

## Steps to reproduce the issue
Follow these steps:
1. Login into an account
2. Create a mapping and click on save
3. The error message will appear.
4. Logout and login again, the saved mapping will appear.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

### PR DESCRIPTION
**Pull request by k2maan**
### Related Issues

Closes #193 

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/import#contribution-guideline)

### CODE REVIEW

File: src/store/modules/user/actions.ts [hunk 1]
```diff
@@ -145,32 +145,35 @@ const actions: ActionTree<UserState, RootState> = {
...
+      // This is needed as it would easy to get app name to categorize mappings
+      const mappingTypesFlip = Object.keys(mappingTypes).reduce((mappingTypesFlip: any, mappingType) => {
+        // Updating fieldMpaaings here in case the API fails 
+        fieldMappings[mappingType] = {};
+        mappingTypesFlip[mappingTypes[mappingType]] = mappingType;
+        return mappingTypesFlip;
+      }, {});
+
+      // To ease the handling, updating the state here in case the API fails, we still have mapping types.
+      commit(types.USER_FIELD_MAPPINGS_UPDATED, fieldMappings)
```
Comment (adityasharma7) [inline src/store/modules/user/actions.ts:160]: Add this to last of method and remove 2 occurrences of commit with single

**Review by adityasharma7 — CHANGES_REQUESTED** [review]

**Review by adityasharma7 — APPROVED** [review]
